export const QUERY_KEYS = {
    PRODUCT_TYPES: 'PRODUCT_TYPES',
    PRODUCTS: 'PRODUCTS',
    AGE_GROUPS: 'AGE_GROUPS',
    TARGET_AUDIENCES: 'TARGET_AUDIENCES',
};

export const KEYS = {
    TOKEN: 'TOKEN',
};
